### ISSUE TITLE
camel case in strings.

### ISSUE THREAD

**Issue by danmarsden** [lushonline/moodle-tool_percipioexternalcontentsync#1]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by lushonline** [comment]
Thanks Dan

**Comment by lushonline** [comment]
Plan is not to fix these as some related to TM
